/** 30 sample questions: [question, [A, B, C, D], correct, category, difficulty, explanation] */
export type SeedQuestion = [string, [string, string, string, string], "A" | "B" | "C" | "D", string, "EASY" | "MEDIUM" | "HARD", string];

export const SEED_QUESTIONS: SeedQuestion[] = [
  ["Which planet is known as the Red Planet?", ["Venus", "Mars", "Jupiter", "Mercury"], "B", "Science", "EASY", "Iron oxide (rust) on Mars' surface gives it a reddish appearance."],
  ["What does HTML stand for?", ["Hyper Trainer Marking Language", "HyperText Markup Language", "High Text Machine Language", "Hyperlink and Text Management Language"], "B", "Technology", "EASY", "HTML — HyperText Markup Language — structures content on the web."],
  ["Who wrote the play 'Romeo and Juliet'?", ["Charles Dickens", "Jane Austen", "William Shakespeare", "Mark Twain"], "C", "Literature", "EASY", "Shakespeare wrote it around 1595."],
  ["What is the chemical symbol for gold?", ["Go", "Gd", "Ag", "Au"], "D", "Science", "EASY", "Au comes from the Latin word 'aurum'."],
  ["Which is the largest ocean on Earth?", ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"], "A", "Geography", "EASY", "The Pacific covers about a third of Earth's surface."],
  ["In which year did the first human land on the Moon?", ["1965", "1969", "1972", "1959"], "B", "History", "EASY", "Apollo 11 landed on 20 July 1969."],
  ["Which data structure works on a First-In-First-Out basis?", ["Stack", "Tree", "Queue", "Graph"], "C", "Technology", "MEDIUM", "A queue removes elements in the order they were added (FIFO)."],
  ["What is the capital of Australia?", ["Sydney", "Melbourne", "Perth", "Canberra"], "D", "Geography", "MEDIUM", "Canberra was purpose-built as the capital as a compromise between Sydney and Melbourne."],
  ["Which gas do plants primarily absorb for photosynthesis?", ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"], "A", "Science", "EASY", "Plants convert CO₂ and water into glucose using sunlight."],
  ["Who painted the Mona Lisa?", ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Michelangelo"], "C", "Art", "EASY", "Leonardo da Vinci painted it in the early 1500s."],
  ["What is the time complexity of binary search on a sorted array?", ["O(n)", "O(log n)", "O(n log n)", "O(1)"], "B", "Technology", "MEDIUM", "Each step halves the search space, giving logarithmic time."],
  ["Which Indian mathematician is known for work on infinite series and number theory, and was a Fellow of the Royal Society?", ["Aryabhata", "Srinivasa Ramanujan", "Brahmagupta", "C. V. Raman"], "B", "History", "MEDIUM", "Ramanujan was elected FRS in 1918."],
  ["What is the smallest prime number?", ["0", "1", "2", "3"], "C", "Mathematics", "EASY", "2 is the only even prime and the smallest prime."],
  ["Which organ in the human body produces insulin?", ["Liver", "Pancreas", "Kidney", "Spleen"], "B", "Science", "MEDIUM", "Beta cells in the pancreas' islets of Langerhans produce insulin."],
  ["Which protocol secures data sent between a browser and a website?", ["FTP", "HTTP", "TLS", "SMTP"], "C", "Technology", "MEDIUM", "TLS (used by HTTPS) encrypts traffic between client and server."],
  ["The Great Barrier Reef is located off the coast of which country?", ["Australia", "Indonesia", "Philippines", "New Zealand"], "A", "Geography", "EASY", "It stretches over 2,300 km along Queensland, Australia."],
  ["Who developed the theory of general relativity?", ["Isaac Newton", "Niels Bohr", "Albert Einstein", "Max Planck"], "C", "Science", "EASY", "Einstein published general relativity in 1915."],
  ["What is 15% of 240?", ["32", "36", "38", "40"], "B", "Mathematics", "EASY", "0.15 × 240 = 36."],
  ["Which empire built Machu Picchu?", ["Aztec", "Maya", "Olmec", "Inca"], "D", "History", "MEDIUM", "The Inca built it in the 15th century in the Andes."],
  ["In Git, which command creates a new branch and switches to it?", ["git branch -d", "git switch -c", "git merge --new", "git checkout --orphan-all"], "B", "Technology", "MEDIUM", "`git switch -c <name>` (or `git checkout -b`) creates and switches to a branch."],
  ["What is the hardest natural substance?", ["Quartz", "Diamond", "Topaz", "Corundum"], "B", "Science", "EASY", "Diamond scores 10 on the Mohs hardness scale."],
  ["Which country has the most natural lakes?", ["Russia", "USA", "Canada", "Finland"], "C", "Geography", "HARD", "Canada has more lakes than the rest of the world combined, by most counts."],
  ["Who is the author of '1984'?", ["Aldous Huxley", "George Orwell", "Ray Bradbury", "H. G. Wells"], "B", "Literature", "EASY", "George Orwell published Nineteen Eighty-Four in 1949."],
  ["What is the sum of the interior angles of a hexagon?", ["540°", "620°", "720°", "900°"], "C", "Mathematics", "MEDIUM", "(n − 2) × 180° = 4 × 180° = 720°."],
  ["Which element has the atomic number 1?", ["Helium", "Oxygen", "Carbon", "Hydrogen"], "D", "Science", "EASY", "Hydrogen has one proton."],
  ["The Treaty of Versailles formally ended which war?", ["World War I", "World War II", "The Crimean War", "The Franco-Prussian War"], "A", "History", "MEDIUM", "It was signed in 1919, ending WWI between Germany and the Allies."],
  ["In SQL, which clause filters rows after aggregation?", ["WHERE", "GROUP BY", "HAVING", "ORDER BY"], "C", "Technology", "HARD", "HAVING filters grouped results; WHERE filters before grouping."],
  ["Which musical instrument has 88 keys in its standard form?", ["Harpsichord", "Organ", "Accordion", "Piano"], "D", "Art", "EASY", "A standard modern piano has 52 white and 36 black keys."],
  ["What is the approximate speed of light in a vacuum?", ["300,000 km/s", "150,000 km/s", "30,000 km/s", "3,000,000 km/s"], "A", "Science", "MEDIUM", "About 299,792 km/s."],
  ["Which number comes next in the sequence 1, 1, 2, 3, 5, 8, 13, …?", ["18", "20", "21", "26"], "C", "Mathematics", "EASY", "Fibonacci: each term is the sum of the two before it (8 + 13 = 21)."],
];
